set(shad_source
    ../src/main.c
    ../src/menu.c
    ../src/color.c
    ../src/label.c
    ../src/state.c
    ../src/button.c
    ../src/canvas.c
    ../src/ncpanel.c
    ../src/palette.c
    ../src/instrument_panel.c
    ../src/shad_error.c
    ../src/color_picker_panel.c
    ../src/selected_color_panel.c)
